const GET_ALL_USER_INFO_REQUEST = "user/GET_ALL_USER_INFO_REQUEST"

const GET_ALL_USER_INFO_SUCCESS = "user/GET_ALL_USER_INFO_SUCCESS"

const GET_ALL_USER_INFO_FAILURE = "user/GET_ALL_USER_INFO_FAILURE"

export {
    GET_ALL_USER_INFO_FAILURE,
    GET_ALL_USER_INFO_SUCCESS,
    GET_ALL_USER_INFO_REQUEST,
    
}